name: interview_application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  autoequal: ^0.5.1
  bloc: ^8.1.2
  dio: ^5.3.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  interview_domain:
    path: ../domain

dev_dependencies:
  autoequal_gen: ^0.5.1
  build_runner: ^2.4.6
  very_good_analysis: ^5.1.0
