name: interview_domain
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  autoequal: ^0.5.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  autoequal_gen: ^0.5.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
